print("===== Program Biodata=====")
print("Nama : Ryan Syaputra")
print("NIM : 2611532006")
print("Kelas : Alpro B")
print("* * * * *")
print("*       *")
print("*       *")
print("*       *")
print("* * * * *")

